;;; themes.scm --- theming, all in userland Scheme.
;;;
;;; The core knows exactly one primitive: (set-face-attribute! face attr val ...).
;;; Everything else — the theme registry, define-theme, load-theme, the
;;; palettes — is Scheme. Faces map to CSS custom properties (--face-attr)
;;; consumed by the frontend.
;;;
;;; Semantic faces: default (bg fg) · window (bg) · modeline (bg fg)
;;;   modeline-active (bg fg) · cursor (bg) · region (bg) · accent (fg)
;;;   dim (fg) · select (bg)

(define *themes* '())

(define (define-theme name faces)
  (set! *themes* (cons (list name faces) *themes*)))

(define (theme-names) (map car *themes*))

(define (load-theme name)
  (let ((t (assoc name *themes*)))
    (if t
        (begin
          (for-each (lambda (spec) (apply set-face-attribute! spec)) (cadr t))
          (message (string-append "Loaded theme " name)))
        (message (string-append "No such theme: " name)))))

;;; --- palettes ---------------------------------------------------------------

(define-theme "paper"                ; the design default (light) — restorable
  (list
    (list 'default 'bg "#e6e0d2" 'fg "#1b1a17")
    (list 'window 'bg "#fdfcf8")
    (list 'window-inactive 'bg "#f4f0e6")
    (list 'modeline 'bg "#eae5da" 'fg "#57534a")
    (list 'modeline-active 'bg "#e7e9f1" 'fg "#1b1a17")
    (list 'cursor 'bg "#26356b")
    (list 'region 'bg "#e7e9f1")
    (list 'accent 'fg "#26356b")
    (list 'dim 'fg "#8a857a")
    (list 'select 'bg "#e7e9f1")
    (list 'hl-line 'bg "#f5f1e6")
    (list 'linenum 'fg "#b3ac9c")
    (list 'border 'bg "#cbc4b1")
    (list 'warn 'fg "#7a5a1a")
    (list 'org-level-1 'fg "#26356b" 'weight "700")
    (list 'org-level-2 'fg "#7a5a1a" 'weight "600")
    (list 'org-level-3 'fg "#3d6b4f" 'weight "600")
    (list 'org-level-4 'fg "#6b3d5b" 'weight "600")
    (list 'org-todo 'fg "#a03020" 'weight "700")
    (list 'org-done 'fg "#3d6b4f" 'decoration "line-through")
    (list 'org-priority 'fg "#7a5a1a" 'weight "600")
    (list 'org-date 'fg "#26356b" 'style "italic")
    (list 'org-tag 'fg "#8a857a")
    (list 'org-checkbox 'fg "#26356b" 'weight "600")
    (list 'org-cookie 'fg "#7a5a1a")
    (list 'org-meta 'fg "#8a857a")
    (list 'fold-marker 'fg "#8a857a")))

(define-theme "paper-night"          ; the design's warm dark
  (list
    (list 'ts-keyword 'fg "#9fb0ea")
    (list 'ts-function 'fg "#efe9dc")
    (list 'ts-string 'fg "#79bd93")
    (list 'ts-comment 'fg "#a79d8c")
    (list 'ts-number 'fg "#d5ac66")
    (list 'ts-constant 'fg "#d5ac66")
    (list 'ts-type 'fg "#d5ac66")
    (list 'ts-module 'fg "#d5ac66")
    (list 'ts-operator 'fg "#9a9182")
    (list 'ts-punctuation 'fg "#9a9182")
    (list 'default 'bg "#100f0c" 'fg "#efe9dc")
    (list 'window 'bg "#201d18")
    (list 'window-inactive 'bg "#161410")
    (list 'modeline 'bg "#2c2822" 'fg "#b3aa99")
    (list 'modeline-active 'bg "#282f4a" 'fg "#efe9dc")
    (list 'cursor 'bg "#9fb0ea")
    (list 'region 'bg "#282f4a")
    (list 'accent 'fg "#9fb0ea")
    (list 'dim 'fg "#a79d8c")
    (list 'select 'bg "#282f4a")
    (list 'hl-line 'bg "#262218")
    (list 'linenum 'fg "#4a443a")
    (list 'border 'bg "#39342b")
    (list 'warn 'fg "#d5ac66")
    (list 'org-level-1 'fg "#9fb0ea" 'weight "700")
    (list 'org-level-2 'fg "#d5ac66" 'weight "600")
    (list 'org-level-3 'fg "#79bd93" 'weight "600")
    (list 'org-level-4 'fg "#c99ac2" 'weight "600")
    (list 'org-todo 'fg "#e0705a" 'weight "700")
    (list 'org-done 'fg "#79bd93" 'decoration "line-through")
    (list 'org-priority 'fg "#d5ac66" 'weight "600")
    (list 'org-date 'fg "#9fb0ea" 'style "italic")
    (list 'org-tag 'fg "#a79d8c")
    (list 'org-checkbox 'fg "#9fb0ea" 'weight "600")
    (list 'org-cookie 'fg "#d5ac66")
    (list 'org-meta 'fg "#a79d8c")
    (list 'fold-marker 'fg "#a79d8c")))

(define-theme "aimax-dark"
  (list
    (list 'ts-keyword 'fg "#7aa2f7")
    (list 'ts-function 'fg "#d6d8de")
    (list 'ts-string 'fg "#9ece6a")
    (list 'ts-comment 'fg "#8b8fa3")
    (list 'ts-number 'fg "#e0af68")
    (list 'ts-constant 'fg "#e0af68")
    (list 'ts-type 'fg "#2ac3de")
    (list 'ts-module 'fg "#2ac3de")
    (list 'ts-operator 'fg "#8b8fa3")
    (list 'ts-punctuation 'fg "#8b8fa3")
    (list 'default 'bg "#1e1f22" 'fg "#d6d8de")
    (list 'window 'bg "#23242a")
    (list 'window-inactive 'bg "#1e1f22")
    (list 'modeline 'bg "#2f3140" 'fg "#8b8fa3")
    (list 'modeline-active 'bg "#3b4261" 'fg "#d6d8de")
    (list 'cursor 'bg "#c0caf5")
    (list 'region 'bg "#31436e")
    (list 'accent 'fg "#7aa2f7")
    (list 'dim 'fg "#8b8fa3")
    (list 'select 'bg "#2c3a5e")
    (list 'hl-line 'bg "#26272e")
    (list 'linenum 'fg "#4a4d59")
    (list 'border 'bg "#15161a")
    (list 'warn 'fg "#e0af68")))

(define-theme "catppuccin-mocha"
  (list
    (list 'ts-keyword 'fg "#cba6f7")
    (list 'ts-function 'fg "#89b4fa")
    (list 'ts-string 'fg "#a6e3a1")
    (list 'ts-comment 'fg "#6c7086")
    (list 'ts-number 'fg "#fab387")
    (list 'ts-constant 'fg "#fab387")
    (list 'ts-type 'fg "#f9e2af")
    (list 'ts-module 'fg "#f9e2af")
    (list 'ts-operator 'fg "#89dceb")
    (list 'ts-punctuation 'fg "#9399b2")
    (list 'default 'bg "#1e1e2e" 'fg "#cdd6f4")
    (list 'window 'bg "#181825")
    (list 'window-inactive 'bg "#11111b")
    (list 'modeline 'bg "#313244" 'fg "#a6adc8")
    (list 'modeline-active 'bg "#45475a" 'fg "#cdd6f4")
    (list 'cursor 'bg "#f5e0dc")
    (list 'region 'bg "#45475a")
    (list 'accent 'fg "#cba6f7")
    (list 'dim 'fg "#6c7086")
    (list 'select 'bg "#313244")
    (list 'hl-line 'bg "#232338")
    (list 'linenum 'fg "#45475a")
    (list 'border 'bg "#11111b")
    (list 'warn 'fg "#fab387")))

(define-theme "tokyo-night"
  (list
    (list 'ts-keyword 'fg "#bb9af7")
    (list 'ts-function 'fg "#7aa2f7")
    (list 'ts-string 'fg "#9ece6a")
    (list 'ts-comment 'fg "#565f89")
    (list 'ts-number 'fg "#ff9e64")
    (list 'ts-constant 'fg "#ff9e64")
    (list 'ts-type 'fg "#2ac3de")
    (list 'ts-module 'fg "#2ac3de")
    (list 'ts-operator 'fg "#89ddff")
    (list 'ts-punctuation 'fg "#565f89")
    (list 'default 'bg "#1a1b26" 'fg "#c0caf5")
    (list 'window 'bg "#16161e")
    (list 'window-inactive 'bg "#1a1b26")
    (list 'modeline 'bg "#24283b" 'fg "#565f89")
    (list 'modeline-active 'bg "#414868" 'fg "#c0caf5")
    (list 'cursor 'bg "#c0caf5")
    (list 'region 'bg "#33467c")
    (list 'accent 'fg "#7aa2f7")
    (list 'dim 'fg "#565f89")
    (list 'select 'bg "#292e42")
    (list 'hl-line 'bg "#1f2029")
    (list 'linenum 'fg "#3b4261")
    (list 'border 'bg "#101014")
    (list 'warn 'fg "#e0af68")))

(define-command "load-theme"
  (lambda ()
    (minibuffer-read "Load theme: " (theme-names)
      (lambda (name) (load-theme name)))))
