[package]
name = "aimax_ts"
version = "0.1.0"
edition = "2021"

[lib]
name = "aimax_ts"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36"
streaming-iterator = "0.1"
libloading = "0.8"
tree-sitter = "0.25"
tree-sitter-language = "0.1"
tree-sitter-elixir = "0.3"
tree-sitter-json = "0.24"
tree-sitter-rust = "0.24"
