;;; peek-md-test.scm --- peeks of markdown files in a group leave dired standing.

(domain! 'testing)
(effects! '(write))

(deftest 'three-peeks-of-markdown-files-leave-dired-in-its-window
  "a writing-mode buffer's setup runs when a peek is replaced; dired must not go"
  (lambda ()
    (t--peek-with
      (lambda ()
        (t--peek-file "one.md" "# one\n\ntext\n")
        (t--peek-file "two.md" "# two\n\ntext\n")
        (t--peek-file "three.md" "# three\n\ntext\n")
        (let ((id (group-record-create! "zz-peek-md")))
          (dired-open t--peek-dir)
          (let ((d (current-buffer))
                (me (active-window)))
            (buffer-add-group! d id)
            (let loop ((i 0))
              (when (and (< i 20) (not (string-suffix? ".md" (or (dired-entry) ""))))
                (list-move-in! d 1)
                (loop (+ i 1))))
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after one peek: in dired")
            (check-true! (popup-open?) "the peek is in the popup")
            (list-move-in! d 1)
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after two: in dired")
            (check-true! (buffer-exists? d) "dired lives")
            (check-equal! (window-buffer me) d "and holds its window")
            (list-move-in! d 1)
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after three: in dired")
            (check-true! (buffer-exists? d) "dired still lives")
            (check-equal! (window-buffer me) d "and still holds its window")
            (check-equal! (length (peek-buffers)) 1 "one peek")
            (run-command "dired-quit")
            (check-equal! (length (peek-buffers)) 0 "q took the peek")
            (check-false! (popup-open?) "and the popup")
            (check-equal! (current-buffer) d "dired stays")
            (buffer-kill! d)
            (group-record-delete! id)))))))

(deftest 'a-peek-keeps-its-mode-when-the-listing-under-it-is-killed
  "killing dired with a peek up leaves the peek a peek, in the popup"
  (lambda ()
    (t--peek-with
      (lambda ()
        (let ((a (t--peek-file "one.md" "# one\n\ntext\n")))
          (dired-open t--peek-dir)
          (let ((d (current-buffer))
                (me (active-window)))
            (let loop ((i 0))
              (when (and (< i 20) (not (equal? (dired-entry) "one.md")))
                (list-move-in! d 1)
                (loop (+ i 1))))
            (run-command "dired-visit")
            (check-true! (peek-buffer? a) "a peek shows")
            (buffer-kill! d)
            (check-true! (peek-buffer? a) "the peek is still a peek")
            (check-equal! (popup-buffer) a "still in the popup")
            (check-false! (equal? (window-buffer me) a)
                          (string-append "the work window did not fall onto it: " (or (window-buffer me) "none")))
            (check-equal! (active-window) me
                          (string-append "and stays selected; active " (number->string (active-window)) " popup " (number->string (or (popup-window) 0))))))))))
