;;; peek-md-test.scm --- peeks of markdown files in a group leave dired standing.

(domain! 'testing)
(effects! '(write))

(deftest 'three-peeks-of-markdown-files-leave-dired-in-its-window
  "a writing-mode buffer's setup runs when a peek is replaced; dired must not go"
  (lambda ()
    (t--peek-with
      (lambda ()
        (t--peek-file "one.md" "# one\n\ntext\n")
        (t--peek-file "two.md" "# two\n\ntext\n")
        (t--peek-file "three.md" "# three\n\ntext\n")
        (let ((id (group-record-create! "zz-peek-md")))
          (dired-open t--peek-dir)
          (let ((d (current-buffer))
                (me (active-window)))
            (buffer-add-group! d id)
            (let loop ((i 0))
              (when (and (< i 20) (not (string-suffix? ".md" (or (dired-entry) ""))))
                (list-move-in! d 1)
                (loop (+ i 1))))
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after one peek: in dired")
            (check-true! (popup-open?) "the peek is in the popup")
            (list-move-in! d 1)
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after two: in dired")
            (check-true! (buffer-exists? d) "dired lives")
            (check-equal! (window-buffer me) d "and holds its window")
            (list-move-in! d 1)
            (run-command "dired-visit")
            (check-equal! (current-buffer) d "after three: in dired")
            (check-true! (buffer-exists? d) "dired still lives")
            (check-equal! (window-buffer me) d "and still holds its window")
            (check-equal! (length (peek-buffers)) 1 "one peek")
            (run-command "dired-quit")
            (check-equal! (length (peek-buffers)) 0 "q took the peek")
            (check-false! (popup-open?) "and the popup")
            (check-equal! (current-buffer) d "dired stays")
            (buffer-kill! d)
            (group-record-delete! id)))))))
